const PRODUCT_DATA = [
  {
    "image": "samosa.png",
    "name": "Förrätter",
    "headname": "Förrätter",
    "rest": " Start your journey into Authentic Indian Foods",
    "rating": "4.5 (164)",
    //"price": " ",
    //"currency": "kr",
    "items": [
      {
        "number": "1.",
        "foodname": "SAMOSA",
        "price": "60",
        "ingredients": "(hemlagad indisk pirorg med vegetarisk fyllning)",
        "ingredientsin": " ",
        "currency": "kr",
      },
      {
        "number": "2.",
        "foodname": "PAKORA",
        "price": "49",
        "ingredients": "(friterad blomkål & aubergine)",
        "ingredientsin": " ",
        "currency": "kr",
      },
      {
        "number": "3.",
        "foodname": "PAPADAM",
        "price": "40",
        "ingredients": "(krispig linschips serveras med mango chutney)",
        "ingredientsin": " ",
        "currency": "kr",
      },
      {
        "number": "4.",
        "foodname": "SOPPA",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Dal",
            "pricein": "69",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Tomat (grädde i)",
            "pricein": "69",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(färsk koriander, lök, vitlök, lime)",
      },
      {
        "number": "5.",
        "foodname": "ONION BHAJI",
        "price": "59",
        "ingredients": "(friterad lök, kryddor med glutenfrimjöl)",
        "ingredientsin": " ",
        "currency": "kr",
      },
      {
        "number": "6.",
        "foodname": "BASONI CHICKEN",
        "price": "75",
        "ingredients": "(grillad kycklingfile friterad med kikärtormjöl)",
        "ingredientsin": " ",
        "currency": "kr",
      },
      {
        "number": "7.",
        "foodname": "CHOP",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Alo (potatis)",
            "pricein": "45",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Ponir (ost)",
            "pricein": "75",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(friterad med indiska kryddor & glutenfrimjöl)",
      },
    ],
  },
  {
    "image": "nun_bread.png",
    "name": "Indisk Bröd",
    "headname": "Indisk Bröd",
    "rest": " Freshly Baked Indian Breads",
    "rating": "4.5 (164)",
    "price": " ",
    //"currency": "\$"
    "items": [
      {
        "number": "8.",
        "foodname": "NAAN",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Sada (vanlig)",
            "pricein": "30",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Garlic (vitlök)",
            "pricein": "35",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(ägg, mjölk, salt, socker)",
      },
      {
        "number": "9.",
        "foodname": "NAAN",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Peshwari (cashewnött & russin)",
            "pricein": "55",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Ponir (ost)",
            "pricein": "55",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(ägg, mjölk, salt, socker)",
      },
      {
        "number": "10.",
        "foodname": "NAAN",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Paranta",
            "pricein": "35",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Peshwari Paranta (cashewnött & russin)",
            "pricein": "65",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Ponir Paranta (ost)",
            "pricein": "65",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(smörstekt ägg, mjölk, salt, socker)",
      },
      {
        "number": "11.",
        "foodname": "MUGHLAI PARANTA (chilli)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": "75",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "köttfärs",
            "pricein": "75",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(smörstekt med ägg, mjölk, salt, socker)",
      },
      {
        "number": "12.",
        "foodname": "NAAN",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Masala (sesam)",
            "pricein": "40",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Vitlök Ponir (ost)",
            "pricein": "65",
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(ägg, mjölk, salt, socker)",
      },
    ],
  },
  {
    "image": "vegan_ratter.png",
    "name": "Vegan Rätter (Mellan / Stark)",
    "headname": "Vegan Rätter (Mellan / Stark)",
    "rest": " Your pure Vegetable Dishes of India",
    "rating": "4.5 (164)",
    "price": " ",
    //"currency": "\$"
    "items": [
      {
        "number": "13.",
        "foodname": "VEG KOFTA (veg bullar)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Curry",
            "pricein": 140,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Balti",
            "pricein": 140,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Korai (stark)",
            "pricein": 140,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Vindalo (stark)",
            "pricein": 140,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(tomat, paparika, lök, vitlök)",
      },
      {
        "number": "14.",
        "foodname": "VEG KOFTA (veg bullar) [mild]",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Korma",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Tikks Masala",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Mango Masala",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": " Jal Masala (stark)",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(tomat, cashewnötter, kokosmjölk, lök, vitlök)",
      },
      {
        "number": "15.",
        "foodname": " ",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Palak Ponir",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Palak Dal",
            "pricein": 140,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Palak Ponir Masala (nötter)",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(spenat, tomat, lök, vitlök, vegan ost)",
      },
      {
        "number": "16.",
        "foodname": "MIX VEG (blandade grönsaker)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Korma",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Tikka Masala",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Mango Masala",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Jal Masala (stark)",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(tomat, cashewnötter, kokosmjölk, lök, vitlök)",
      },
      {
        "number": "17.",
        "foodname": "PONIR (veganost)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Korma",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Tikka Masala",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Mango Masala",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Jal Masala (stark)",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(tomat, cashewnötter, kokosmjölk, lök, vitlök)",
      },
      {
        "number": "18.",
        "foodname": "VEGAN TANDORRI KEBAB SIZLAR",
        "price": 165,
        "ingredients": " ",
        "itemsin": [],
        "currency": "kr",
        "ingredientsin":
            "(blandade grönsöker, tandoori kryddor serveras i het järn platta)",
      },
    ],
  },
  {
    "image": "grill_ratter.png",
    "name":
        "GRILL RÄTTER SERVERAS PÅ JÄRN PLATTA MED GRÖNSAKSSALLAD, CASHEWNÖTT SÅS",
    "headname": "GRILL RÄTTER SERVERAS PÅ JÄRN PLATTA MED . .",
    "rest": " Special grills the Indian way",
    "rating": "4.5 (164)",
    "price": " ",
    //"currency": "\$"
    "items": [
      {
        "number": "19.",
        "foodname": "TANDORI CHICKEN KLUBBORI SIZLAR",
        "price": 165,
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": "(grillad kycklingklubbor med yoghurt, lime, tandori)",
      },
      {
        "number": "20.",
        "foodname": "TANDORI TIKKA SIZLAR",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 220,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 199,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lax",
            "pricein": 199,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Mix Chicken",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(grillad file med yoghurt, lime, tandori)",
      },
      {
        "number": "21.",
        "foodname": "HOT TANDORI TIKKA SIZLAR",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 169,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 225,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 210,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lax",
            "pricein": 210,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(chili, yoghurt, lime, tandori)",
      },
      {
        "number": "22.",
        "foodname": "GARLIC TIKKA SIZLAR",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 220,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 199,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(vitlök marinerad)",
      },
      {
        "number": "23.",
        "foodname": "HOT GARLIC TIKKA SIZLAR",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 169,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 225,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 210,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(vitlök, chili marinerad)",
      },
      {
        "number": "24.",
        "foodname": "KEBAB SIZLAR",
        "price": 185,
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": "(grillad köttfärs kebab med yoghurt, lime, tandori)",
      },
      {
        "number": "25.",
        "foodname": "MIXED SIZLAR",
        "price": 220,
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": "(kyckling, lamm, kungsräkor, yoghurt, tandori)",
      },
      {
        "number": "26.",
        "foodname": "CHEESY CHICKEN TIKKA SIZLAR",
        "price": 190,
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": "(ost, yoghurt, tandroi med grillad kycklingfile)",
      },
    ],
  },
  {
    "image": "redford_thali.png",
    "name": "REDFORD SPECIAL MIX THALI",
    "headname": "REDFORD SPECIAL MIX THALI",
    "rest": " Get a taste of the Indian Thali",
    "rating": "4.5 (164)",
    "price": 360,
    //"currency": "\$"
    "items": [
      {
        "number": "27.",
        "foodname": "MIXED THALI",
        "price": 220,
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin":
            "(onion bhaji med mintsäs, grillad lamm, chicken, kungsräkor, vitlöks naan, cashewnött sås)",
      },
      {
        "number": "28.",
        "foodname": "MIXGRYTA THALI",
        "price": 220,
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin":
            "(onion bhaji, mintsås, chicken tikka masala, lamm korai, biff korma, vitlöks naan)",
      },
      {
        "number": "29.",
        "foodname": "VEGETERISK THALI",
        "price": 220,
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin":
            "(onion bhaji, mintsås, palak ponir, kofta korma, kikärtor dopiaza, vitlöks naan)",
      },
    ],
  },
  {
    "image": "biryani2.png",
    "name": "BIRYANI RÄTTER (Mellan/Stark)",
    "headname": "BIRYANI RÄTTER (Mellan/Stark)",
    "rest": " Delicious Indian Biryanis",
    "rating": "4.5 (164)",
    "price": 360,
    //"currency": "\$"
    "items": [
      {
        "number": "30.",
        "foodname": "BIRYANI",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 150,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Beef",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Veg",
            "pricein": 145,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(stektris, special kryddor, lök, cashewnöttsås)",
      },
    ],
  },
  {
    "image": "special_grytta.png",
    "name": "REDFORD SPECIAL GRYTA (Laktos)",
    "headname": "REDFORD SPECIAL GRYTA (Laktos)",
    "rest": " Mouthwatering Indian Curries",
    "rating": "4.5 (164)",
    "price": 360,
    //"currency": "\$"
    "items": [
      {
        "number": "31.",
        "foodname": "TIKKA BUTTER MASALA",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 145,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "KOFTA (köttbullar)",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lax",
            "pricein": 185,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(yoghurt, grädde, tomat, cashewnötter)",
      },
      {
        "number": "32.",
        "foodname": "HOT TIKKA BUTTER MASALA (mellan/stark)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 150,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 180,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "KOFTA (köttbullar)",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lax",
            "pricein": 190,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(chilli, yoghurt, grädde, tomat, cashewnötter)",
      },
      {
        "number": "33.",
        "foodname": "TIKKA BUTTER JAL MASALA (stark)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 180,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 180,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lax",
            "pricein": 190,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(paprika, lök, yoghurt, grädde, chili, cashewnötter)",
      },
      {
        "number": "34.",
        "foodname": "GARLIC TIKKA BUTTER MASALA",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 145,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(garlic, yoghurt, grädde, tomat, cashewnötter)",
      },
      {
        "number": "35.",
        "foodname": "HOT GARLIC TIKKA BUTTER MASALA",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 150,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 180,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "KOFTA (köttbullar)",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin":
            "(chili, garlic, yoghurt, grädde, tomat, cashewnötter)",
      },
      {
        "number": "36.",
        "foodname": "GARLIC BUTTER JAL MASALA (stark)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 180,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 180,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(garlic, yoghurt, grädde, tomat, cashewnötter)",
      },
      {
        "number": "37.",
        "foodname": "MANGO BUTTER MASALA",
        "price": " ",
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 185,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 185,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lax",
            "pricein": 195,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Mix Veg",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(mango, yoghurt, grädde, cashewnötter)",
      },
      {
        "number": "38.",
        "foodname": "KORMA",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Mix Veg",
            "pricein": 145,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(yoghurt, kokos, tomat, cashewnötter)",
      },
      {
        "number": "39.",
        "foodname": "CHILLI KORMA",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 180,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Mix Veg",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(chilli, yoghurt, kokos, tomat, cashewnötter)",
      },
      {
        "number": "40.",
        "foodname": "MANGO BALTI",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 185,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 185,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lax",
            "pricein": 195,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Mix Veg",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(yoghurt, grädde, cashewnötter, mango)",
      },
    ],
  },
  {
    "image": "curry_gryta.png",
    "name": "CURRY GRYTA (Mellan / Stark)",
    "headname": "CURRY GRYTA (Mellan / Stark)",
    "rest": " Indian Unique Balti & Korai recipes",
    "rating": "4.5 (164)",
    "price": 360,
    //"currency": "\$"
    "items": [
      {
        "number": "41.",
        "foodname": "KORAI (stark)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Garlic Chicken",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Chilli Garlic Chicken",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Chicken",
            "pricein": 145,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "KOFTA (köttbullar)",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Mix Veg",
            "pricein": 140,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(lök, paprika, tomat, chilli, vitlök)",
      },
      {
        "number": "42.",
        "foodname": "BALTI",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 145,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 175,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Ponir (ost)",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Mix Veg",
            "pricein": 140,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(lök, paprika, tomat, ingefära, vitlök)",
      },
      {
        "number": "43.",
        "foodname": "SAMBAL MASALA",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 145,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Räkor",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Dal (linser)",
            "pricein": 135,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(lök, tomat, ingefära, vitlök, sambal)",
      },
      {
        "number": "44.",
        "foodname": "MADRASI MASALA (mellan / stark)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Mix Veg",
            "pricein": 140,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(chilli, yoghurt, tomat, ingefära & Indisk kryddor)",
      },
      {
        "number": "45.",
        "foodname": "SAAG GOSHT (spenat) / SABJI GOSHT (grönsaker)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 145,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Garlic Chicken",
            "pricein": 150,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Räkor",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(spenat, tomat, lök, ingefära, vitlök)",
      },
      {
        "number": "46.",
        "foodname": "VINDALO (stark)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 150,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lax",
            "pricein": 185,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(chilli, tomat, lök, vitlök)",
      },
      {
        "number": "47.",
        "foodname": "ROGAN JHOSH",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 150,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(yoghurt, tomat, lök, ingefära, vitlök)",
      },
      {
        "number": "48.",
        "foodname": "HIMALAYA (chilli)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 160,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kungsräkor",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "KOFTA (köttbullar)",
            "pricein": 165,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(tomat, lök, paprika, vitlök, kokos)",
      },
      {
        "number": "49.",
        "foodname": "CURRY / CURRY ACHARI (mellan / stark)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Chicken",
            "pricein": 145,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Lamm",
            "pricein": 170,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Biff",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(paprika, lök, tomat, curry)",
      },
    ],
  },
  {
    "image": "vegeteriska_ratter.png",
    "name": "VEGETARISKA RÄTTER",
    "headname": "VEGETARISKA RÄTTER",
    "rest": " Fresh Veg dishes with Indian Dairy",
    "rating": "4.5 (164)",
    "price": 360,
    //"currency": "\$"
    "items": [
      {
        "number": "50.",
        "foodname": "PALAK (spenat)",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Ponir (ost)",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Chana (kikärtor vegan)",
            "pricein": 140,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Balti Ponir (ost)",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(spenat, tomat, grädde, ingefära)",
      },
      {
        "number": "51.",
        "foodname": "TIKKA BUTTER MASALA",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Ponir (ost)",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kofta (bullar)",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Chana Ponir (kikärtor)",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(yoghurt, tomat, grädde, cashewnötter)",
      },
      {
        "number": "52.",
        "foodname": "JALFRAZI",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Ponir (ost)",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kofta (bullar)",
            "pricein": 149,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Chana Ponir (kikärtor)",
            "pricein": 145,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(tomat, lök, grädde, vitlök, chilli)",
      },
      {
        "number": "53.",
        "foodname": "MANGO TIKKA BUTTER MASALA",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "Ponir (ost)",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "Kofta (bullar)",
            "pricein": 155,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": "(yoghurt, mango, grädde, cashewnötter)",
      },
    ],
  },
  {
    "image": "extra_tillbehor.png",
    "name": "EXTRA TILLBEHÖR",
    "headname": "EXTRA TILLBEHÖR",
    "rest": " Tangy tastes of Chutney, Salads and Pickles",
    "rating": "4.5 (164)",
    "price": 360,
    //"currency": "\$"
    "items": [
      {
        "number": "54.",
        "foodname": "RAITA",
        "price": "35",
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": "(yoghurt blandad med Indisk kryddor)",
      },
      {
        "number": "55.",
        "foodname": " ",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "CHILLI PICKLES",
            "pricein": 30,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "MANGO CHUTNEY",
            "pricein": 30,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "MINTSÅS",
            "pricein": 30,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": " ",
      },
      {
        "number": "56.",
        "foodname": " ",
        "price": " ",
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [
          {
            "infoodname": "EXTRA RIS",
            "pricein": 25,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "SAFFRAN RIS",
            "pricein": 35,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": " ",
      },
      {
        "number": "57.",
        "foodname": " ",
        "price": " ",
        "ingredients": " ",
        "currency": " ",
        "itemsin": [
          {
            "infoodname": "EXTRA SALLAD",
            "pricein": 15,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
          {
            "infoodname": "STEKT GRÖNSAKSSALLAD",
            "pricein": 30,
            "ingredientsin": " ",
            "currencyin": "kr",
          },
        ],
        "ingredientsin": " ",
      },
    ],
  },
  {
    "image": "barn_ratter.png",
    "name": "BARN RÄTTER (Gäller 6-8 År)",
    "headname": "BARN RÄTTER (Gäller 6-8 År)",
    "rest": " Indian Dishes For The Kids \n      (Specially Made)",
    "rating": "4.5 (164)",
    "price": 360,
    //"currency": "\$"
    "items": [
      {
        "number": "58.",
        "foodname": "CHICKEN TIKKA MASALA",
        "price": "95",
        "ingredients": "(yoghurt, grädde, cashewnötter)",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": " ",
      },
      {
        "number": "59.",
        "foodname": "CHICKEN KORMA",
        "price": "95",
        "ingredients": "(yoghurt, kokos, grädde, cashewnötter)",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": " ",
      },
      {
        "number": "60.",
        "foodname": "TANDOORI CHICKEN",
        "price": "95",
        "ingredients": "(grillad kyckling med cashewnött sås)",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": " ",
      },
    ],
  },
  {
    "image": "efter_ratter.png",
    "name": "EFTER RÄTTER",
    "headname": "EFTER RÄTTER",
    "rest": " Indian Icy Fresh Lassi & Drinks",
    "rating": "4.5 (164)",
    "price": 360,
    //"currency": "\$"
    "items": [
      {
        "number": "61.",
        "foodname": "MANGO LASSI",
        "price": "55",
        "ingredients": "(yoghurt dryck med mango)",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": " ",
      },
      {
        "number": "62.",
        "foodname": "VANILJ GLASS",
        "price": "55",
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": " ",
      },
      {
        "number": "63.",
        "foodname": "KULFI",
        "price": "55",
        "ingredients": "(hemlagad Indisk glass)",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": " ",
      },
      {
        "number": "64.",
        "foodname": "GAZAR HALWA",
        "price": "55",
        "ingredients": "(morot mjölk, socker serveras med vanilj glass)",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": " ",
      },
      {
        "number": "65.",
        "foodname": "CHAE",
        "price": "55",
        "ingredients": "(Indiskte)",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": " ",
      },
      {
        "number": "66.",
        "foodname": "KAFFE",
        "price": "30",
        "ingredients": " ",
        "currency": "kr",
        "itemsin": [],
        "ingredientsin": " ",
      },
    ],
  },
];

/*const CATEGORIES = [
  {"image": "salad.png", "name": "Salad"},
  {"image": "fastfood.png", "name": "Fast Food"},
  {"image": "desert.png", "name": "Desert"},
  {"image": "drinks.png", "name": "Drinks"},
  {"image": "drinks.png", "name": "Drinks"},
];*/
